# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: 每一个不曾起舞的日子，都是对生命的辜负。
title: 分享技术，收获快乐
subtitle: Subtitle
name: 码农乐享 # ex. DONGChuan
email: codeenjoy_mail@163.com
description: description
keywords: keywords
encoding: "utf-8"
favicon: favicon.ico 

# location: My location # ex. Nice, France
# company: MyCompany
# company_url: my_company_website

# github_username: # ex. DONGChuan
github_url: my_github_url # ex. https://github.com/DONGChuan
repository: github_username/github_username.github.io # ex. DONGChuan/DONGChuan.github.io
enforce_ssl: enforce_ssl

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  # enable_coderay: true

# Disque
# disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
# Navigation. top menu list
menus:

  # -
    # href: /link.html
    # label: 友链
    # target: _self

  -
    href: /about.html
    label: 关于
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  # -
    # href: /open-source
    # label: Open-Source

  # -
  #   href: /spring-boot.html
  #   label: Spring Boot
  #   target: _self
  #   subnav:

  #     -
  #       subHref: /spring-boot.html
  #       subLabel: Spring Boot

  #     -
  #       subHref: /spring-cloud.html
  #       subLabel: Spring Cloud

  - 
    # href: /
    # label: Certificate
    # target: _self
    # subnav:

    -
      # subHref: /mandarin
      # subHref: /mandarin.html
      # subLabel: Mandarin

      # comprehensive_quality、
    -
      # subHref: /comprehensive_quality
      # subHref: /comprehensive_quality.html
      # subLabel: Comprehensive<br>Quality

  -
    href: /
    label: Java
    target: _self
    subnav:

    -
      subHref: /java_se_tutorial.html
      subLabel: Java 教程

    # -
      # subHref: /java_se.html
      # subLabel: Java 基础

    # -
      # subHref: /
      # subLabel: JavaWeb
  
  # -
  #   href: /
  #   label: Spring
  #   target: _self
  #   subnav:

  #   -
  #     subHref: /
  #     subLabel: SpringBoot

  #   -
  #     subHref: /
  #     subLabel: SpringCloud

  -
    # href: /
    # label: Bigdata
    # target: _self
    # subnav:

    -
      # subHref: /bigdata
      # subHref: /bigdata.html
      # subLabel: Bigdata

    
    -
      # subHref: /hadoop
      # subHref: /hadoop.html
      # subLabel: Hadoop

    -
      # subHref: /zookeeper
      # subHref: /zookeeper.html
      # subLabel: Zookeeper

    -
      # subHref: /flink
      # subHref: /flink.html
      # subLabel: Flink

  # -
    # href: /blog
    # label: Blog

  # -
    # href: /bookmark
    # label: Bookmark

  -
    href: /archives.html
    label: Archives

  # -
    # href: /about.html
    # label: About


# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show


# Google Analytics
# analytics :
  # provider : google
  # google :
      # tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
